# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.frequency_constraint import FrequencyConstraint


class CentralFrequency(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, frequency_constraint: FrequencyConstraint=None, central_frequency: int=None):  # noqa: E501
        """CentralFrequency - a model defined in Swagger

        :param frequency_constraint: The frequency_constraint of this CentralFrequency.  # noqa: E501
        :type frequency_constraint: FrequencyConstraint
        :param central_frequency: The central_frequency of this CentralFrequency.  # noqa: E501
        :type central_frequency: int
        """
        self.swagger_types = {
            'frequency_constraint': FrequencyConstraint,
            'central_frequency': int
        }

        self.attribute_map = {
            'frequency_constraint': 'frequency-constraint',
            'central_frequency': 'central-frequency'
        }

        self._frequency_constraint = frequency_constraint
        self._central_frequency = central_frequency

    @classmethod
    def from_dict(cls, dikt) -> 'CentralFrequency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The central-frequency of this CentralFrequency.  # noqa: E501
        :rtype: CentralFrequency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def frequency_constraint(self) -> FrequencyConstraint:
        """Gets the frequency_constraint of this CentralFrequency.


        :return: The frequency_constraint of this CentralFrequency.
        :rtype: FrequencyConstraint
        """
        return self._frequency_constraint

    @frequency_constraint.setter
    def frequency_constraint(self, frequency_constraint: FrequencyConstraint):
        """Sets the frequency_constraint of this CentralFrequency.


        :param frequency_constraint: The frequency_constraint of this CentralFrequency.
        :type frequency_constraint: FrequencyConstraint
        """

        self._frequency_constraint = frequency_constraint

    @property
    def central_frequency(self) -> int:
        """Gets the central_frequency of this CentralFrequency.


        :return: The central_frequency of this CentralFrequency.
        :rtype: int
        """
        return self._central_frequency

    @central_frequency.setter
    def central_frequency(self, central_frequency: int):
        """Sets the central_frequency of this CentralFrequency.


        :param central_frequency: The central_frequency of this CentralFrequency.
        :type central_frequency: int
        """

        self._central_frequency = central_frequency
