# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.wavelength_reference import WavelengthReference
from swagger_server.models.obfn import Obfn
from swagger_server import util


class ObfnParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, obfn_pool: List[Obfn]=None, wavelength_reference_pool: List[WavelengthReference]=None):  # noqa: E501
        """ObfnParameters - a model defined in Swagger

        :param obfn_pool: The obfn_pool of this ObfnParameters.  # noqa: E501
        :type obfn_pool: List[Obfn]
        :param wavelength_reference_pool: The wavelength_reference_pool of this ObfnParameters.  # noqa: E501
        :type wavelength_reference_pool: List[WavelengthReference]
        """
        self.swagger_types = {
            'obfn_pool': List[Obfn],
            'wavelength_reference_pool': List[WavelengthReference]
        }

        self.attribute_map = {
            'obfn_pool': 'obfn-pool',
            'wavelength_reference_pool': 'wavelength-reference-pool'
        }

        self._obfn_pool = obfn_pool
        self._wavelength_reference_pool = wavelength_reference_pool

    @classmethod
    def from_dict(cls, dikt) -> 'ObfnParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The obfn-parameters of this ObfnParameters.  # noqa: E501
        :rtype: ObfnParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def obfn_pool(self) -> List[Obfn]:
        """Gets the obfn_pool of this ObfnParameters.


        :return: The obfn_pool of this ObfnParameters.
        :rtype: List[Obfn]
        """
        return self._obfn_pool

    @obfn_pool.setter
    def obfn_pool(self, obfn_pool: List[Obfn]):
        """Sets the obfn_pool of this ObfnParameters.


        :param obfn_pool: The obfn_pool of this ObfnParameters.
        :type obfn_pool: List[Obfn]
        """

        self._obfn_pool = obfn_pool

    @property
    def wavelength_reference_pool(self) -> List[WavelengthReference]:
        """Gets the wavelength_reference_pool of this ObfnParameters.


        :return: The wavelength_reference_pool of this ObfnParameters.
        :rtype: List[WavelengthReference]
        """
        return self._wavelength_reference_pool

    @wavelength_reference_pool.setter
    def wavelength_reference_pool(self, wavelength_reference_pool: List[WavelengthReference]):
        """Sets the wavelength_reference_pool of this ObfnParameters.


        :param wavelength_reference_pool: The wavelength_reference_pool of this ObfnParameters.
        :type wavelength_reference_pool: List[WavelengthReference]
        """

        self._wavelength_reference_pool = wavelength_reference_pool
