# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.central_frequency import CentralFrequency
from swagger_server import util


class WavelengthReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, wavelength_id: int=None, central_frequency: CentralFrequency=None):  # noqa: E501
        """WavelengthReference - a model defined in Swagger

        :param wavelength_id: The wavelength_id of this WavelengthReference.  # noqa: E501
        :type wavelength_id: int
        :param central_frequency: The central_frequency of this WavelengthReference.  # noqa: E501
        :type central_frequency: CentralFrequency
        """
        self.swagger_types = {
            'wavelength_id': int,
            'central_frequency': CentralFrequency
        }

        self.attribute_map = {
            'wavelength_id': 'wavelength-id',
            'central_frequency': 'central-frequency'
        }

        self._wavelength_id = wavelength_id
        self._central_frequency = central_frequency

    @classmethod
    def from_dict(cls, dikt) -> 'WavelengthReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The wavelength-reference of this WavelengthReference.  # noqa: E501
        :rtype: WavelengthReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wavelength_id(self) -> int:
        """Gets the wavelength_id of this WavelengthReference.


        :return: The wavelength_id of this WavelengthReference.
        :rtype: int
        """
        return self._wavelength_id

    @wavelength_id.setter
    def wavelength_id(self, wavelength_id: int):
        """Sets the wavelength_id of this WavelengthReference.


        :param wavelength_id: The wavelength_id of this WavelengthReference.
        :type wavelength_id: int
        """

        self._wavelength_id = wavelength_id

    @property
    def central_frequency(self) -> CentralFrequency:
        """Gets the central_frequency of this WavelengthReference.


        :return: The central_frequency of this WavelengthReference.
        :rtype: CentralFrequency
        """
        return self._central_frequency

    @central_frequency.setter
    def central_frequency(self, central_frequency: CentralFrequency):
        """Sets the central_frequency of this WavelengthReference.


        :param central_frequency: The central_frequency of this WavelengthReference.
        :type central_frequency: CentralFrequency
        """

        self._central_frequency = central_frequency
