# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.arof import Arof


class ArofParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, arof_pool: List[Arof]=None):  # noqa: E501
        """ArofParameters - a model defined in Swagger

        :param arof_pool: The arof_pool of this ArofParameters.  # noqa: E501
        :type arof_pool: List[Arof]
        """
        self.swagger_types = {
            'arof_pool': List[Arof]
        }

        self.attribute_map = {
            'arof_pool': 'arof-pool'
        }

        self._arof_pool = arof_pool

    @classmethod
    def from_dict(cls, dikt) -> 'ArofParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The arof-parameters of this ArofParameters.  # noqa: E501
        :rtype: ArofParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def arof_pool(self) -> List[Arof]:
        """Gets the arof_pool of this ArofParameters.


        :return: The arof_pool of this ArofParameters.
        :rtype: List[Arof]
        """
        return self._arof_pool

    @arof_pool.setter
    def arof_pool(self, arof_pool: List[Arof]):
        """Sets the arof_pool of this ArofParameters.


        :param arof_pool: The arof_pool of this ArofParameters.
        :type arof_pool: List[Arof]
        """

        self._arof_pool = arof_pool
